# This file was generated by GoReleaser. DO NOT EDIT.
cask "stash" do
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/vrypan/stash/releases/download/v#{version}/stash_#{version}_darwin_x86_64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "2fc486d6b5e1cc77b0e6641cacc4e6721fcac5bd47dda726a8a03e38d9eef6e2"
    end
    on_arm do
      url "https://github.com/vrypan/stash/releases/download/v#{version}/stash_#{version}_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "c32bf4b8054841e55bf5b8a034d5029ffa15669caf16ee36eda181ad64054557"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vrypan/stash/releases/download/v#{version}/stash_#{version}_linux_x86_64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "93a5a3aee2cb516ff1648236e55fa17f9853dd486dcb82580b640aba47bc75e5"
    end
    on_arm do
      url "https://github.com/vrypan/stash/releases/download/v#{version}/stash_#{version}_linux_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "9e6448d2d2d368cba4ba16eedada226de6ab56d97e5efc0b96c28a6eab19c92b"
    end
  end

  name "stash"
  desc "A local store for pipeline output and ad hoc file snapshots."
  homepage "https://github.com/vrypan/stash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stash"]
    end
  end

  # No zap stanza required

end
