# This file was generated by GoReleaser. DO NOT EDIT.
cask "stash" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/vrypan/stash/releases/download/v#{version}/stash_#{version}_darwin_x86_64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "88a96e69e61ddf5bb8bb9f9fbe4dcf4dbdc609ffa8bba42c77c1010069b6a41f"
    end
    on_arm do
      url "https://github.com/vrypan/stash/releases/download/v#{version}/stash_#{version}_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "156930fa221aca171981650a5a81676e49ebcb63d137a0eab2f72de659109455"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vrypan/stash/releases/download/v#{version}/stash_#{version}_linux_x86_64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "36d484f6f2c0f60c9ccadb7428e46c881c996f155c88cc7499ae59d9ae974b56"
    end
    on_arm do
      url "https://github.com/vrypan/stash/releases/download/v#{version}/stash_#{version}_linux_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "95c9b05e530e359db74c55e6a1191d4038f0ea1be675f96053ec4548618ef424"
    end
  end

  name "stash"
  desc "A local store for pipeline output and ad hoc file snapshots."
  homepage "https://github.com/vrypan/stash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stash"]
    end
  end

  # No zap stanza required

end
