# This file was generated by GoReleaser. DO NOT EDIT.
cask "stash" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/vrypan/stash/releases/download/v#{version}/stash_#{version}_darwin_x86_64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "313528bd2a9d7f69a13a0decc984aa57f8482ea61939d26d00d40a30d9fbf015"
    end
    on_arm do
      url "https://github.com/vrypan/stash/releases/download/v#{version}/stash_#{version}_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "09785c2f7e6ae4c959a4fd99cc0e3508dd57f13aed8b92cbcbc3bb0d23972ee7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vrypan/stash/releases/download/v#{version}/stash_#{version}_linux_x86_64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "70518a00077f6eaebf030276e182ff961ea8047cea1d426c1070d015ad1f4344"
    end
    on_arm do
      url "https://github.com/vrypan/stash/releases/download/v#{version}/stash_#{version}_linux_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "7ef563323bd7e4331edfe5463ca05d8f26b3d7f1ac5b7c81e5ac516968ffd48f"
    end
  end

  name "stash"
  desc "A local store for pipeline output and ad hoc file snapshots."
  homepage "https://github.com/vrypan/stash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stash"

  # No zap stanza required

end
