# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FcAppkey < Formula
  desc "Farcaster Application Key Generator"
  homepage "https://github.com/vrypan/fc-appkey"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/fc-appkey/releases/download/v0.1.4/fc-appkey_Darwin_x86_64.tar.gz"
      sha256 "61abda99d0f910afa9494cb777b2ba98d0d885c962fd9f7930a643e762a7e29e"

      def install
        bin.install "fc-appkey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/fc-appkey/releases/download/v0.1.4/fc-appkey_Darwin_arm64.tar.gz"
      sha256 "c6774b3ca100858f7b0cbabd7d55160740b72158d4356bab0ae8bf5de9efb0d6"

      def install
        bin.install "fc-appkey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/fc-appkey/releases/download/v0.1.4/fc-appkey_Linux_x86_64.tar.gz"
      sha256 "ad3d9943ac73c14fa3542fdc5922a16b4b30db82e40c4fb74cf607bb773834e0"
      def install
        bin.install "fc-appkey"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/fc-appkey/releases/download/v0.1.4/fc-appkey_Linux_arm64.tar.gz"
      sha256 "5888e9ae09f8bd8e1bb316cce14b9c4b97d8df28bc2ba4912ae0c094ac23367c"
      def install
        bin.install "fc-appkey"
      end
    end
  end

  test do
    system "#{bin}/fc-appkey", "--version"
  end
end
