# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FcAppkey < Formula
  desc "Farcaster Application Key Generator"
  homepage "https://github.com/vrypan/fc-appkey"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/fc-appkey/releases/download/v0.1.3/fc-appkey_Darwin_x86_64.tar.gz"
      sha256 "62b9de1bd7becde0002a913ea374f6f4c26451874d0f39bccf85710ce08a5370"

      def install
        bin.install "fc-appkey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/fc-appkey/releases/download/v0.1.3/fc-appkey_Darwin_arm64.tar.gz"
      sha256 "71f075d5cf35a5f94fb24363dcb81414afa80518aa88f445affc2e15e418e894"

      def install
        bin.install "fc-appkey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/fc-appkey/releases/download/v0.1.3/fc-appkey_Linux_x86_64.tar.gz"
      sha256 "818b756fc6daa076310033c4f1cad27cf679f46799ad9fc4247bf36bd2131e27"
      def install
        bin.install "fc-appkey"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/fc-appkey/releases/download/v0.1.3/fc-appkey_Linux_arm64.tar.gz"
      sha256 "871b6b798c59d87ba6f4ab25cca9fac0f1f4e809f8e87d2f528930146a77f747"
      def install
        bin.install "fc-appkey"
      end
    end
  end

  test do
    system "#{bin}/fc-appkey", "--version"
  end
end
