# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FcAppkey < Formula
  desc "Farcaster Application Key Generator"
  homepage "https://github.com/vrypan/fc-appkey"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/fc-appkey/releases/download/v0.1.5/fc-appkey_Darwin_x86_64.tar.gz"
      sha256 "3e73b6b2e29fec5db92ba180f870cc50c6792f76a78f4d5c248b246ac80ed86e"

      def install
        bin.install "fc-appkey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/fc-appkey/releases/download/v0.1.5/fc-appkey_Darwin_arm64.tar.gz"
      sha256 "b0d3bd677bc980a93b315e4f06c0d5b13f2c5de8a5f570c43f1027e42a358006"

      def install
        bin.install "fc-appkey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/fc-appkey/releases/download/v0.1.5/fc-appkey_Linux_x86_64.tar.gz"
      sha256 "833caf245a31258f2a3317df854265454bc53e6ddd976db1043903544a0f8f52"
      def install
        bin.install "fc-appkey"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/fc-appkey/releases/download/v0.1.5/fc-appkey_Linux_arm64.tar.gz"
      sha256 "84940260f714accf91484fe07380f8b3137b5ced14ca4a53de95c47a7f9526b7"
      def install
        bin.install "fc-appkey"
      end
    end
  end

  test do
    system "#{bin}/fc-appkey", "--version"
  end
end
