# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fcp < Formula
  desc "Copy data from/to farcaster and the local filesystem"
  homepage "https://github.com/vrypan/fcp"
  version "1.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vrypan/fcp/releases/download/v1.1.3/fcp_Darwin_x86_64.tar.gz"
      sha256 "46311ffa0102532658302d5b4e2b45f1822abe8ec49906f02756aedcced2b08d"

      def install
        bin.install "fcp"
        bin.install "fcp-inspect"
      end
    end
    on_arm do
      url "https://github.com/vrypan/fcp/releases/download/v1.1.3/fcp_Darwin_arm64.tar.gz"
      sha256 "e394ba659a76955d0666bb60300edae7bbe7f0064ff137bc6cd2a500102ef856"

      def install
        bin.install "fcp"
        bin.install "fcp-inspect"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/fcp/releases/download/v1.1.3/fcp_Linux_x86_64.tar.gz"
        sha256 "f12a082aa3f858be8b0690313e92b6bb7caa77ee335e110bc822c49324a95d0a"

        def install
          bin.install "fcp"
          bin.install "fcp-inspect"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/fcp/releases/download/v1.1.3/fcp_Linux_arm64.tar.gz"
        sha256 "c2b025abdf486517fc33bbb2918a39deb248239c4919dea13a183ef50aea07c8"

        def install
          bin.install "fcp"
          bin.install "fcp-inspect"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Both binaries have been installed:
        - fcp → `fcp --help`
        - fcp-inspect → `fcp-inspect --help`
    EOS
  end

  test do
    system "#{bin}/fcp --version"
    system "#{bin}/fcp-inspect --version"
  end
end
