# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fcp < Formula
  desc "Copy data from/to farcaster and the local filesystem"
  homepage "https://github.com/vrypan/fcp"
  version "1.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vrypan/fcp/releases/download/v1.1.2/fcp_Darwin_x86_64.tar.gz"
      sha256 "474001722e6a6b9a48e2ac49227ca6028de46cbb52788928a9c0dd6a6d1f36bb"

      def install
        bin.install "fcp"
        bin.install "fcp-inspect"
      end
    end
    on_arm do
      url "https://github.com/vrypan/fcp/releases/download/v1.1.2/fcp_Darwin_arm64.tar.gz"
      sha256 "1c6e654dfdd1e8215d1d6ed3a466233a0775e22e728873ce606ae280f9811070"

      def install
        bin.install "fcp"
        bin.install "fcp-inspect"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/fcp/releases/download/v1.1.2/fcp_Linux_x86_64.tar.gz"
        sha256 "9fb1dcf775354b3ac4b324dcf97f0dbefdd94769fab2a341a1a24773258ddaa5"

        def install
          bin.install "fcp"
          bin.install "fcp-inspect"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/fcp/releases/download/v1.1.2/fcp_Linux_arm64.tar.gz"
        sha256 "a9f7a203d9c5d1b01221fd5b9ec879a187ed87f651a26f0c33d920bf4876449b"

        def install
          bin.install "fcp"
          bin.install "fcp-inspect"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Both binaries have been installed:
        - fcp → `fcp --help`
        - fcp-inspect → `fcp-inspect --help`
    EOS
  end

  test do
    system "#{bin}/fcp --version"
    system "#{bin}/fcp-inspect --version"
  end
end
