# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lemon3 < Formula
  desc "lemon3 is a filesharing system using Farcaster and IPFS."
  homepage "https://github.com/vrypan/lemon3"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vrypan/lemon3/releases/download/v0.4.1/lemon3_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "fa0628ecd9f3dc45a71957b4bc1a69ce2d070d9a412ec1a9fbebaec3b8b01caa"

      def install
        bin.install "lemon3"
      end
    end
    on_arm do
      url "https://github.com/vrypan/lemon3/releases/download/v0.4.1/lemon3_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "c8ade211e306739857e40b20fda9ec40474dd3af1c3cac7a6491d0554c0814c6"

      def install
        bin.install "lemon3"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/lemon3/releases/download/v0.4.1/lemon3_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "30f7aad5b6c3919285d72811221a0d29b2bb6d0475c7a28d7916890a938f4ef0"

        def install
          bin.install "lemon3"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/lemon3/releases/download/v0.4.1/lemon3_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "454d8e1d430ecb2e47f1c7cc3cdc56f4396a44b2937be74e9ecfb8364bf67434"

        def install
          bin.install "lemon3"
        end
      end
    end
  end

  def caveats
    <<~EOS
      lemon3 --help
    EOS
  end

  test do
    system "#{bin}/lemon3 version"
  end
end
