# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScMon < Formula
  desc "sc-mon monitors the status of a Snapchain node."
  homepage "https://github.com/vrypan/sc-mon"
  version "0.1.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vrypan/sc-mon/releases/download/v0.1.4/sc-mon_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "88c50f43f9a9c53fa97a8a823f8714d9c31a0697432762a53fd56593af80bf14"

      def install
        bin.install "sc-mon"
      end
    end
    on_arm do
      url "https://github.com/vrypan/sc-mon/releases/download/v0.1.4/sc-mon_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "abbfd56c92c359d160f0dec28d739453879294814ff1abf013131357445eb4ce"

      def install
        bin.install "sc-mon"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/sc-mon/releases/download/v0.1.4/sc-mon_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "5e3b8910e5566a24040e640408cb8857924e68c3ddf7d2cfe7dcdc87dbc2a309"

        def install
          bin.install "sc-mon"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/sc-mon/releases/download/v0.1.4/sc-mon_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "faef9ddcf30e05315d6391c9ffc5aba7952247b0c37bab3b0c48415b9b8bffb7"

        def install
          bin.install "sc-mon"
        end
      end
    end
  end

  def caveats
    <<~EOS
      sc-mon --help
    EOS
  end

  test do
    system "#{bin}/sc-mon version"
  end
end
