# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnappubTools < Formula
  desc "A set of tools that implement the basic functionality of snappub"
  homepage "https://github.com/vrypan/snappub-tools"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/snappub-tools/releases/download/v0.2.2/snappub-tools_Darwin_x86_64.tar.gz"
      sha256 "84eca591f937e613131df3d070ce5aece490b47c1b7506933ead3208d496190f"

      def install
        bin.install "snappub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/snappub-tools/releases/download/v0.2.2/snappub-tools_Darwin_arm64.tar.gz"
      sha256 "ab9a323eac5b6de2730f074859628830f87060d9d21661ab500bd67d426e6a21"

      def install
        bin.install "snappub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/snappub-tools/releases/download/v0.2.2/snappub-tools_Linux_x86_64.tar.gz"
      sha256 "280fbddb0c70f07d609f045a8dc88f94bf32079dc9cb4fed209a210aa3c17fc2"
      def install
        bin.install "snappub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/snappub-tools/releases/download/v0.2.2/snappub-tools_Linux_arm64.tar.gz"
      sha256 "04cc264bb9da59a5a7dc9b2723c47cf15f1de661924d89ebf16888223745ad39"
      def install
        bin.install "snappub"
      end
    end
  end

  test do
    system "#{bin}/snappub", "--version"
  end
end
