# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnappubTools < Formula
  desc "A set of tools that implement the basic functionality of snappub"
  homepage "https://github.com/vrypan/snappub-tools"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/snappub-tools/releases/download/v0.1.0/snappub-tools_Darwin_x86_64.tar.gz"
      sha256 "d20c3b7d151e5716233ca4c317e6cedb6ca378c8556a10ea0a2bf3887a625f24"

      def install
        bin.install "snappub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/snappub-tools/releases/download/v0.1.0/snappub-tools_Darwin_arm64.tar.gz"
      sha256 "031fb8d196e0a2cbe27995b62aff564d670ebaf0f50dafa0b73aa8bf09828512"

      def install
        bin.install "snappub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/snappub-tools/releases/download/v0.1.0/snappub-tools_Linux_x86_64.tar.gz"
      sha256 "17db4ea8403406588b87a2e374dc8608671a3b6c86706bf6cceefebf4d3ca452"
      def install
        bin.install "snappub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/snappub-tools/releases/download/v0.1.0/snappub-tools_Linux_arm64.tar.gz"
      sha256 "ef9b2566426a34e317bacb8af170f3cc09cb9e57ed17dda15288536cc6ef3af8"
      def install
        bin.install "snappub"
      end
    end
  end

  test do
    system "#{bin}/snappub", "--version"
  end
end
